spring:
  application:
    name: web-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1900/eureka/

server:
  port: 3000

management:
  endpoints:
    web:
      exposure:
        include: '*'
